[windows]
laptop-windows11 ansible_host=51.182.90.142

[windows:vars]
ansible_user=ansible
ansible_password={{ lookup('env', 'ANSIBLE_WIN_PASSWORD') }}
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5986
