[windows]
laptop-windows11 ansible_host=193.186.4.82

[windows:vars]
ansible_user=ansible
ansible_password={{ lookup('env', 'ANSIBLE_WIN_PASSWORD') }}
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=validate
ansible_port=5986
