name: Deploy Web App to MLDEV

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

jobs:
  deploy:
    # Target your specific runner using its labels
    runs-on: [self-hosted]

    defaults:
      run:
        shell: powershell -ExecutionPolicy Bypass -File "{0}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          ls .
          # npm install
          # Or your specific build commands

      # - name: Deploy Application
      #   run: |
      #     # Command to restart your web app or copy files
      #     # Example for a simple Node app:
      #     pm2 restart my-web-app || pm2 start app.js --name "my-web-app"
