name: Deploy Web App to MLDEV

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

jobs:
  deploy:
    # Target your specific runner using its labels
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo ${{ github.workspace }}
          ls .
          npm install

      # - name: Run Application
      #   run: |
      #     npm run dev
