name: Deploy IIS via Ansible

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch: # Permite execução manual

jobs:
  ansible-deploy:
    runs-on: [Ansible]
    permissions:
      contents: write    
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4    

      - name: Gerar arquivo
        run: |        
          mkdir geraarquivo
          echo "arquivo gerado" >> geraarquivo/teste.txt
          ls ./geraarquivo/

      - name: Executar Playbook de configuração e deploy
        env:
          ANSIBLE_WIN_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
        run: |
          ansible-playbook ansible/setup_iis.yml \
            -i ansible/inventory.ini \
            -vvv
