name: Deploy IIS via Ansible

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch: # Permite execução manual

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Executar Playbook
        env:
          ANSIBLE_WIN_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}      
        run: |
          ansible-playbook -vvv -i ansible/inventory.ini ansible/setup_iis.yml
